### ISSUE TITLE
Reproducible results with ask and tell

### ISSUE THREAD

**Issue by MichelV2** [facebookresearch/nevergrad#181] opened 2019-04-16 15:50 UTC
Hello,

Is there a way to make optimization results reproducible when using the ask and tell interface? We've tried to set seeds using random.seed() and numpy.random.seed() just before using ask and tell with  but did not succeed in fixing the output.

Thank you

**Comment by jrapin** [comment] 2019-04-17 15:57
If you seed at the start of the optimization, you should still have reproducible results as long as your function evaluations:
- are seedable as well.
- do not remove the random seed through something like `np.random.seed(None)`. At some point we will probably add and use an internal random state for optimizers to be more robust to this (cf discussion #4 )

Does your function satisfies those conditions? If yes, this is weird. What is your function and which optimizer are you using?

On a side note, most algorithms are seeded with `np.random.seed`. A few ("recast" algorithms, currently this means `scipy` based algorithms such as `SQP`, `COBYLA` etc) may (or may need, I did not check) need `random.seed` as well.

**Comment by jrapin** [comment] 2019-04-30 13:07
Closing for lack of activity, please reopen with more details if you still need information ;)

**Comment by MichelV2** [comment] 2019-05-03 10:14
Hi Jeremy,

Thank you for your answer. We noticed that initial parameters are different when re-running our script even though we seed before the "ask" function. Here is an excerpt of the code:



	np.random.seed(123)
	rn.seed(456)

	optimizer = optimization.registry[tool[i]](dimension=dimension, budget=budget)
	print("Running optimization using ", tool[i], "\n")
	
	for j in range(optimizer.budget):
		x = optimizer.ask()
		value = train_and_return_test_error_mixed(x)
		optimizer.tell(x, value)
		args, kwargs = train_and_return_test_error_mixed.convert_to_arguments(x, deterministic=True)



Is there a way we could make initialization reproducible or to fix the parameters at the first iteration? 

Thank you

**Comment by jrapin** [comment] 2019-05-03 12:41
Can you detail what you mean by "initialization" and which optimizer(s) you use?
I am not aware of any initialization that is cannot be seeded this way, there is even a test which seeds, runs a few iterations and compares with previous runs for each algorithm:
https://github.com/facebookresearch/nevergrad/blob/19c8a3770319503b0f9d166f537327350c82b318/nevergrad/optimization/test_optimizerlib.py#L120-L149

I try to consider `Instrumentation` as the source of stochasticity as it is not tested as thoroughly as the optimizers, but I could not think of anything that could have gone wrong there either :s

What is inside your function?
I would probably need a full running example to help debugging this I think :s 

Also, you should consider moving to nevergrad 2.0.0+, which has a better interface for instrumentation (or so I hope ;) )

**Comment by MichelV2** [comment] 2019-05-21 08:17
Hi Jeremy,

We're updating nevergrad and will use the new instrumentation interface. Thanks for your help!

**Comment by jrapin** [comment] 2019-05-28 14:37
Now all optimizers (apart from `scipy`-based optimizers `NelderMead`, `Cobyla`, `SQP` and `Powell`) have there own random state (on the master branch), so that there should not be any external interference anymore.

I'm closing this for now since I am lacking information to help, I hope the problem will have disappeared with this change. If it didn't, please reopen and provide some toy example ;)

**Closed by jrapin** 2019-05-28 14:37 UTC
